# Generated by Django 4.2.4 on 2023-08-18 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
