# Generated by Django 4.2.4 on 2023-08-18 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_rename_users_groups'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='groups',
            table='groups',
        ),
    ]
