# Generated by Django 4.2.4 on 2023-08-18 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_users_user_alter_user_table'),
        ('groups', '0003_alter_groups_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='admins',
            field=models.ManyToManyField(related_name='admin_groups', to='user.user'),
        ),
        migrations.AddField(
            model_name='groups',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='creator_groups', to='user.user'),
        ),
        migrations.AddField(
            model_name='groups',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='groups',
            name='members',
            field=models.ManyToManyField(related_name='groups', to='user.user'),
        ),
    ]
