# Generated by Django 4.2.4 on 2023-08-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_users_user_alter_user_table'),
        ('groups', '0004_groups_admins_groups_creator_groups_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='groups',
            name='admins',
            field=models.ManyToManyField(related_name='groups_admin', to='user.user'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='members',
            field=models.ManyToManyField(related_name='groups_member', to='user.user'),
        ),
    ]
