# Generated by Django 4.2.4 on 2023-08-18 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_groups_description_alter_groups_admins_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'ordering': ['-date_created']},
        ),
    ]
